MOBILE_WORK_DIR=$1
CAFFE_MODEL=$2
CAFFE_WEIGHT=$3
MODEL_NAME=$4
PRECISON=$5
LOG_PATH=$6

adb shell "mkdir $MOBILE_WORK_DIR"
adb push $CAFFE_MODEL $MOBILE_WORK_DIR
adb push $CAFFE_WEIGHT $MOBILE_WORK_DIR
adb shell "./data/evaluate_service/tools/caffe2bolt $MOBILE_WORK_DIR $MODEL_NAME $PRECISON"   >$LOG_PATH/omg.log
