from .architecture import transform_architecture
from .combiner import ConnectionsArchParamsCombiner
from .prune_arch import Conv2dPruneArchitecture, BatchNorm2dPruneArchitecture
from .double_channels_arch import Conv2dDoubleChannelArchitecture, BatchNorm2dDoubleChannelArchitecture
